version: '3.9'

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: ai-concierge-postgres
    environment:
      POSTGRES_DB: concierge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ai-concierge-redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    container_name: ai-concierge-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-concierge-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - backend/.env
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
      - minio
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-concierge-frontend
    command: npm run dev -- --host 0.0.0.0
    environment:
      VITE_API_BASE_URL: /api
      VITE_API_PROXY_TARGET: http://backend:8000
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata:
  miniodata:
