name: ci-cd

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ai-concierge-deploy
  cancel-in-progress: true

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  PROJECT_NAME: ai-concierge
  ECR_REPOSITORY: ai-concierge-backend
  FRONTEND_BUCKET: ${{ secrets.FRONTEND_BUCKET }}
  ANALYTICS_BUCKET: ${{ secrets.ANALYTICS_BUCKET }}
  TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
  TF_STATE_KEY: ai-concierge/terraform.tfstate

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest pytest-asyncio httpx

      - name: Run backend tests
        working-directory: backend
        run: PYTHONPATH=$PWD python -m pytest

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Type check frontend
        working-directory: frontend
        run: npm run typecheck

  build:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build backend image
        id: build_image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          cd backend
          IMAGE_URI="${REGISTRY}/${ECR_REPOSITORY}:${GITHUB_SHA}"
          echo "Building image: ${IMAGE_URI}"
          docker build -t "${IMAGE_URI}" -t "${REGISTRY}/${ECR_REPOSITORY}:latest" .
          docker push "${IMAGE_URI}"
          docker push "${REGISTRY}/${ECR_REPOSITORY}:latest"
          echo "image_uri=${IMAGE_URI}" >> "$GITHUB_OUTPUT"
          echo "Built and pushed: ${IMAGE_URI}"

    outputs:
      image_uri: ${{ steps.build_image.outputs.image_uri }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Validate image URI
        run: |
          echo "Using image URI: '${{ needs.build.outputs.image_uri }}'"
          if [ -z "${{ needs.build.outputs.image_uri }}" ]; then
            echo "ERROR: image_uri is EMPTY!"
            exit 1
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Resolve ECS role ARNs
        id: roles
        run: |
          EXEC_ROLE_ARN=$(aws iam get-role --role-name "${PROJECT_NAME}-ecs-execution" --query 'Role.Arn' --output text)
          TASK_ROLE_ARN=$(aws iam get-role --role-name "${PROJECT_NAME}-ecs-task" --query 'Role.Arn' --output text)
          echo "execution_role=${EXEC_ROLE_ARN}" >> "$GITHUB_OUTPUT"
          echo "task_role=${TASK_ROLE_ARN}" >> "$GITHUB_OUTPUT"

      - name: Render task definition
        env:
          IMAGE_URI: ${{ needs.build.outputs.image_uri }}
          EXECUTION_ROLE_ARN: ${{ steps.roles.outputs.execution_role }}
          TASK_ROLE_ARN: ${{ steps.roles.outputs.task_role }}
          AWS_REGION: ${{ env.AWS_REGION }}
          BACKEND_ENV_JSON: ${{ secrets.BACKEND_ENV_JSON }}
          BACKEND_SECRET_JSON: ${{ secrets.BACKEND_SECRET_JSON }}
          PROJECT_NAME: ${{ env.PROJECT_NAME }}
        run: |
          python scripts/render_task_definition.py \
            --family "${PROJECT_NAME}-backend" \
            --image "${IMAGE_URI}" \
            --cpu "512" \
            --memory "1024" \
            --execution-role "${EXECUTION_ROLE_ARN}" \
            --task-role "${TASK_ROLE_ARN}" \
            --log-group "/ecs/${PROJECT_NAME}-backend" \
            --log-region "${AWS_REGION}" \
            --environment-json env:BACKEND_ENV_JSON \
            --secret-json env:BACKEND_SECRET_JSON \
            --output taskdef.json

      - name: Register task definition
        id: register
        run: |
          TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json file://taskdef.json --query 'taskDefinition.taskDefinitionArn' --output text)
          echo "task_definition=${TASK_DEF_ARN}" >> "$GITHUB_OUTPUT"
          echo "Registered task definition: ${TASK_DEF_ARN}"

      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster "${PROJECT_NAME}-cluster" \
            --service "${PROJECT_NAME}-service" \
            --task-definition "${{ steps.register.outputs.task_definition }}" \
            --force-new-deployment
          aws ecs wait services-stable --cluster "${PROJECT_NAME}-cluster" --services "${PROJECT_NAME}-service"

      - name: Build frontend
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
        working-directory: frontend
      - run: npm run build
        working-directory: frontend

      - name: Upload frontend to S3
        run: aws s3 sync frontend/dist s3://${FRONTEND_BUCKET} --delete
